### ISSUE TITLE
Error using Security sample OAuth

### ISSUE THREAD

**Issue by orossini** [Esri/arcgis-runtime-samples-dotnet#218]
I'm trying to use the OAuth Authentication sample but it doesn't work on android.
The UWP works fine, but Android raised an error : Error 400 Invalid request.
The login UI appears, and the user can specify login and password. But clicking the connect button raises this error.

Trying to debug it, I used fiddler to trace network traffic between emulator and server.
It appears that the oauthorize request parameters contain "response_type=token" instead of "response_type=code" as mentionned in the doc (https://developers.arcgis.com/authentication/mobile-and-native-user-logins/#authorization-example)
Is it normal?

**Comment by ThadT** [comment]
Thanks @orossini I'll give this a look. I remember having some issues with OAuth on Android as well

**Comment by ThadT** [comment]
@orossini 
I beleive the problem is the redirect URI ("http://myapps.portalmapapp"). I recently modified the (ArcGIS Online) app settings to remove that redirect URI and added a new one ("https://developers.arcgis.com"). I updated the code to use the new url and it worked as expected.
You can pull changes from the master branch or just make this change in your code:
`private const string OAuthRedirectUrl = "https://developers.arcgis.com";`

Please update this issue if you continue to have problems. Thanks!

**Comment by orossini** [comment]
@ThadT 
Thanks for your answer.
But I still have the same issue on my side.
Please note that I was talking about the Xamarin.Forms (shared) sample (https://github.com/Esri/arcgis-runtime-samples-dotnet/tree/master/src/Forms/Shared/Samples/Security/OAuth) even it's almost the same as the sample you've just updated.
Sorry if I was not clear in my previous comment.
In my case I use this sample with my appid, webmap id, etc....
As I mentionned it works on the UWP app but not on the Android app.
Because It raises an "invalid request error" and because those two apps don't send the same request parameters to the server (response_type value is different), I was thinking about this parameter value as a potential source of the problem.
Is there a way to force this request parameter by code ?

**Comment by ThadT** [comment]
@orossini 
Sorry for the confusion, I should have realized you were using Forms when you mentioned both Android and UWP!
I ran the Android and UWP versions of the Forms OAuth project and I see the `response_type=token` in the request for both. I'm also able to successfully load a secure web map in both versions of the app. The `token` response  provides the access token directly (instead of requiring the 2-step process of exchanging an authorization code for the token).
I previously had problems with running Android apps on my device because it's 64 bit. You can work around that if you exclude 64-bit apps in the project properties (proj properties > Android options > Advanced > clear arm64-8a and x86_64). 
I also had problems with an OAuth app running in the emulator (would crash after entering login). In that case, I haven't yet found the exact cause of the problem, but found that if Fiddler is set up to see the emulator traffic, the app works. Otherwise it fails ... something about going thru the proxy makes it work.

Sorry I don't have anything more specific for you. Feel free to contact me directly at ttilton@esri.com and I can help you troubleshoot more. I'll update this issue with any helpful info or solutions we find in case anyone else can benefit from it. -Thanks!

**Comment by ThadT** [comment]
**FYI - for those who might run into this problem.**

The Xamarin platforms require a redirect URL that represents a valid address. So, while a redirect URL like `urn:ietf:wg:oauth:2.0:oob` or `http://my.random.redirect.url` will work in your WPF or UWP apps, Android and iOS require a URL that represents an actual endpoint, such as `https://developers.arcgis.com` (iOS also requires an `https` URL).
I'm doing more research on this to see if there's a way to work around it ... I'm not sure if this is something required by the Xamarin.Auth components. It may be that building your own OAuth UI allows you to use the arbitrary redirect URLs. 

I'll update this issue if I find anything useful (and perhaps put it in a blog on GeoNet).
